"""Deep category-specific content for PEPTIQ catalogs.
Each category has its own market intelligence, use cases, personas, objections, and family marker.
"""

DEEP = {
    # ═══════════════════════════════════════════════════════════════════════
    'WOLVERINE': {
        'intro_h2_em': 'reparación celular.',
        'intro_lede': 'Cuatro moléculas que tu paciente atleta o post-operatorio reconoce: <b>BPC-157</b> (gold standard regenerativo · 1,200+ estudios), <b>TB-500</b> (Thymosin β4 · migración celular), <b>KPV</b> (anti-inflamatorio sin inmunosupresión) y <b>NAD+</b> (mitocondrial sistémico). Protocolos validados para tendón crónico, lesión deportiva, post-cirugía ortopédica, gut healing y recuperación atlética alto rendimiento.',
        'mi_eyebrow': 'Market Intelligence · Medicina deportiva + traumatología MX',
        'mi_h2': 'El paciente que invierte en <em class="italic">recuperar primero.</em>',
        'mi_lede': 'El mercado de fisioterapia y medicina deportiva en México facturó <b>USD 1.2 bn en 2024</b> con CAGR <b>+8% a 2029</b> (Statista MX 2025). Post-COVID, las clínicas de recuperación deportiva triplicaron demanda de protocolos científicamente validados. <b>BPC-157 es el péptido más estudiado del mundo</b> · referencia obligada en clínicas elite de USA · gap evidente en MX que tu clínica puede cerrar.',
        'mi_stats': [
            ('1,200+', 'Estudios preclínicos BPC-157', 'Sikiric et al. (Universidad Zagreb) 1991-2024 · referente absoluto regeneración tisular peptídica'),
            ('+40%', 'Reducción tiempo recuperación tendón', 'Comparado con fisioterapia convencional · documentado en tendinopatía crónica (Pevec et al. 2021)'),
            ('220k', 'Cirugías ortopédicas/año MX', 'CONAMED 2024 · de las cuales ~30% reportan recuperación lenta · oportunidad clara'),
        ],
        'levers': [
            ('Lever #1 · BPC-157 es el péptido más estudiado · ya no es nicho',
             '1,200+ estudios preclínicos desde 1991. Acelera angiogénesis vía VEGFR2, reduce inflamación sistémica sin inmunosupresión, repara mucosa GI. En USA está en protocolos de clínicas de NFL/NBA. La clínica MX que lo integre como add-on captura el segmento atleta máster con ticket premium.'),
            ('Lever #2 · Athletes máster (40-55) · explosión post-COVID',
             'Crossfitters, runners y deportistas amateurs 40-55 representan el +40% del mercado wellness recovery (Mexican Sports Medicine Society 2024). Pacientes con disposición a pagar $5-15k MXN/sesión por recuperación premium · ya no aceptan ibuprofeno + reposo.'),
            ('Lever #3 · Post-cirugía ortopédica · gap regenerativo',
             '220k cirugías ortopédicas/año en MX (CONAMED 2024). Aproximadamente 30% reporta recuperación lenta o cicatrización subóptima. Protocolo BPC-157 + TB-500 post-LCA / menisco / Aquiles reduce dropout y acelera return-to-sport. Posicionamiento defensible vs fisioterapia plana.'),
        ],
        'use_cases': [
            ('🦴 Lesiones tendinosas crónicas', 'Tendinitis, epicondilitis, fascitis plantar, Aquiles. BPC-157 SC local + sistémica · 4-6 semanas. <b>Ticket protocolo:</b> $9,000-15,000 MXN/paciente.'),
            ('🩹 Post-cirugía ortopédica (LCA · menisco · hombro)', 'Stack BPC-157 + TB-500 6-8 semanas post-quirúrgico. Reduce tiempo return-to-sport 30%+. <b>Add-on premium</b> sobre cirujano traumatólogo.'),
            ('🏃 Recuperación atlética alto rendimiento', 'Atletas máster · pre-competencia + post-entrenamiento intenso. NAD+ IV pre-evento · BPC-157 SC mantenimiento. Tickets repetidos $4-8k MXN/sesión.'),
            ('🧬 Gut healing · síndrome intestino permeable', 'BPC-157 oral/sublingual + KPV. Indicado SIBO, colitis, post-antibióticos crónicos, gastritis crónica. Cross-sell con dermatólogos (acné inflamatorio sistémico).'),
            ('💔 Heridas crónicas · úlceras', 'TB-500 + BPC-157 tópico/SC. Pacientes diabéticos con úlceras de presión, post-quemaduras grado 2-3. Aplicación geriátrica con protocolo 8-12 semanas.'),
            ('❤️ Post-cirugía cardíaca · TB-500 documentado', 'TB-500 mejora función ventricular post-IAM (Bock-Marquette 2004). Stack con BPC-157 acelera recuperación post-bypass. Indicación experimental en cardiología regenerativa.'),
        ],
        'personas': [
            ('Médico deportivo boutique', '35-50 · clínica recovery 1-2 cabinas · 80-150 pac/mes · Polanco/MTY/GDL · ticket $3-8k', 'Pacientes que se "atoraron" con fisio convencional, buscan algo más. Compite contra centros de regen plasma rica en plaquetas (PRP).', 'Add-on BPC-157 SC al PRP · diferenciador "uso péptidos research-grade con COA" · paciente paga +$3-5k al ticket sin invertir en hardware.'),
            ('Cirujano ortopédico / traumatólogo', '40-60 · ticket $30-80k cirugía · 60-100 pac/mes · referencia post-quirúrgica', 'Pierde control del paciente al fisio · resultado de cirugía depende de recuperación que no controla. Quejas de cicatrización lenta dañan reputación.', 'Protocolo post-quirúrgico premium · vende BPC + TB-500 8 sem como add-on $12-18k MXN. Mantiene paciente en su circuito · acelera return-to-sport.'),
            ('Fisioterapeuta deportivo elite', '32-48 · trabaja con atletas profesionales · ticket sesión $1.5-3k · ~250 sesiones/mes', 'Mercado saturado de fisios genéricos. Atleta exige resultado en 4-6 sem · plataforma actual no escala el ROI.', 'Stack BPC + NAD+ + TB-500 para atletas máster · ticket paquete 6-8 sesiones $20-35k MXN · convierte fisio en "performance lab".'),
        ],
        'objections': [
            ('"¿Está aprobado en México?"',
             'Research-grade · for research use only. El paciente firma consentimiento informado · tu clínica usa el péptido bajo criterio médico profesional. PEPTIQ aporta COA + dossier científico para tu defensa documental.'),
            ('"¿Cuánto tarda en notarse?"',
             'BPC-157: tendón mejora 50% en 2-3 sem · 80% en 4-6 sem (Sikiric 2018). Es de los péptidos con respuesta más rápida documentada. Si el paciente no nota en 3 semanas, revisamos protocolo contigo.'),
            ('"¿Y el COFEPRIS?"',
             'Mismo marco que cualquier péptido research-grade en clínicas privadas. Lote con COA Janoshik · facturación CFDI · documentación lista para auditoría. Te apoyamos con marco legal y consent forms.'),
        ],
        'family_estas_aqui': 'WOLVERINE',
    },
    # ═══════════════════════════════════════════════════════════════════════
    'HIGHLANDER': {
        'intro_h2_em': 'la longevidad celular.',
        'intro_lede': 'Cinco moléculas que el paciente C-suite ya googleó: <b>NAD+</b> (mitocondrial · 7 sirtuinas), <b>Epithalon</b> (telomérico · ciclo Khavinson), <b>Semax</b> (BDNF nootropic), <b>GHK-Cu</b> (modulación 4,192 genes longevidad) y <b>BPC-157</b> (gut-brain axis). Protocolos validados para biological age reversal, IV drip longevity, neuroprotección, sueño profundo y restauración mitocondrial.',
        'mi_eyebrow': 'Market Intelligence · Longevity + Anti-aging MX',
        'mi_h2': 'El pivote de "anti-aging" <em class="italic">a "biological age reversal".</em>',
        'mi_lede': 'El mercado global de longevity facturó <b>USD 27 bn en 2024</b> con forecast <b>$44 bn a 2029</b> (Bloomberg Intelligence). Bezos invirtió $3 bn en Altos Labs · Branson y Sinclair pusieron NAD+ en mainstream. En México, el segmento C-suite 50+ con poder adquisitivo $80-250k/mes representa el sweet spot · clínicas que se posicionan como "longevity center" cobran ticket trimestre $40-80k MXN.',
        'mi_stats': [
            ('USD 44bn', 'Mercado longevity 2029', 'Bloomberg Intelligence · creciendo desde $27bn en 2024 (CAGR +10%)'),
            ('-50%', 'Decline NAD+ entre 40 y 60 años', 'Documentado en humanos · Verdin et al. (Buck Institute) · justifica reposición parenteral'),
            ('+22%', 'Wellness ejecutivo C-suite 50+', 'Crecimiento últimos 2 años (Euromonitor 2025) · ticket promedio 3× vs 2020'),
        ],
        'levers': [
            ('Lever #1 · "Anti-aging" perdió tracción · "biological age reversal" gana',
             'L\'Oréal rebrandeó Lancôme × Timeline como "mitochondrial skincare". El paciente premium ya no compra "verme menos vieja" · compra "regenero mi biología celular medible con biomarcadores". Las clínicas que pivotan capturan +25-40% del ticket sin invertir en hardware.'),
            ('Lever #2 · NAD+ mainstream · IV drip = servicio bandera',
             'Branson, Bezos y David Sinclair han posicionado NAD+ en cultura mainstream. Clínicas premium que ofrecen IV drip 60-90 min con ticket $4-8k MXN reportan +$120k USD/año solo de esta modalidad. Servicio de alto margen + experiencia VIP.'),
            ('Lever #3 · Epithalon · gap evidente en mercado MX',
             'Único péptido con evidencia preclínica de reactivación telomerasa humana (Khavinson · St. Petersburg Institute). Competencia casi nula en MX. Clínicas pioneras posicionadas como "longevity specialists" con ticket trimestre $40-80k MXN sostenible.'),
        ],
        'use_cases': [
            ('🩺 IV drip NAD+ longevity (servicio signature)', '500-1000mg infusión 60-90 min · pacientes recurrentes mensuales. <b>Ticket sesión:</b> $4,000-8,000 MXN. Clínicas que lo ofrecen facturan +$120k USD/año solo en esta modalidad.'),
            ('🕰️ Ciclo Khavinson Epithalon · 4 ciclos/año', '10 días on / 20 días off · 5-10mg SC nocturno. Telomérico + restauración melatonina. <b>Ticket trimestre:</b> $12,000-20,000 MXN/paciente recurring.'),
            ('🧠 Cognitive longevity · Semax intranasal', 'Pacientes ejecutivos C-suite con fatiga cognitiva, jet-lag, deterioro cognitivo leve familiar. 200-600mcg intranasal · ciclos 14-21 días. Cross-sell con anti-aging.'),
            ('⚡ Post-COVID fatiga crónica · long COVID', 'Stack NAD+ IV + BPC-157 sistémico. Pacientes con fatiga, brain fog y disautonomía post-COVID. Mercado huérfano · 5-10% de la población lo padece.'),
            ('✈️ Pre/post jet-lag C-suite ejecutivos', 'NAD+ IV + Semax intranasal antes y después de vuelos transatlánticos. Servicio premium para fortune-500 traveling executives · membership Elite anual.'),
            ('📊 Programa biological age quarterly', 'Stack completo NAD+ + Epithalon + GHK-Cu sistémico · 12 semanas con biomarcadores antes/después (TruDiagnostic, Horvath clock). <b>Ticket programa:</b> $40,000-80,000 MXN.'),
        ],
        'personas': [
            ('Médico longevity center premium', '45-60 · clínica boutique high-end · pacientes C-suite 50+ · ticket $8-25k/sesión', 'Pacientes ya conocen NAD+ y Epithalon · si la clínica no entrega COA del lote, pierde credibilidad vs USA. Compite contra Bulletproof Wellness y Forever Young.', 'COA Janoshik del lote específico al paciente · diferenciador moat. Posicionamiento "el único en MX con esto". Cobra premium sobre clínicas sin COA.'),
            ('Clinical lipidologist / preventive cardiologist', '40-55 · enfoque metabólico-cardiovascular · ticket $5-12k/consulta · 100-150 pac/mes', 'Pacientes high-functioning quieren más que estatinas. Lipid panel + glucose normal pero "se sienten cansados". Mercado huérfano de soluciones celulares.', 'NAD+ + Epithalon como capa preventiva. Stack 12 sem · biomarcadores pre/post. Convierte lipid clinic en "metabolic longevity center".'),
            ('Wellness physician para corporates fortune-500', '38-55 · trabaja con C-suite ejecutivos · ticket retainer $50-150k MXN/año por ejecutivo', 'Clientes pagan retainer alto pero protocolo es "vitaminas + hormonas". Necesitan diferenciador científico para justificar ticket.', 'Programa biological age quarterly · NAD+ IV + Epithalon ciclos · membership Elite. Convierte concierge en "human optimization lab".'),
        ],
        'objections': [
            ('"¿Realmente reactiva telómeros?"',
             'Khavinson 1980-presente · estudios preclínicos consistentes en elongación telómera y restauración melatonina pineal. Ciclo 10-on/20-off es el protocolo validado · te entregamos dossier completo con papers.'),
            ('"¿NAD+ IV vs NAD+ oral?"',
             'IV: bioavailability ~95% · pico inmediato. Oral: ~25%. Para pacientes que pagan ticket premium, IV es el estándar. Oral funciona como mantenimiento entre infusiones.'),
            ('"Mi paciente ya toma NMN suplemento"',
             'NMN es precursor · NAD+ es directo. Ambos son compatibles. Tu paciente NMN-user es el lead caliente para upgrade a IV NAD+ porque ya cree en la tesis · solo le faltaba la dosis terapéutica.'),
        ],
        'family_estas_aqui': 'HIGHLANDER',
    },
    # ═══════════════════════════════════════════════════════════════════════
    'PRIME': {
        'intro_h2_em': 'el rendimiento masculino.',
        'intro_lede': 'Cinco moléculas para el paciente hombre 40+ que invierte en composición corporal y energía: <b>CJC+Ipamorelin</b> (GH stack nocturno · pulso fisiológico), <b>Tesamorelin</b> (FDA-approved · grasa visceral), <b>Ipamorelin</b> (GHRP selectivo · sin cortisol), <b>NAD+</b> (mitocondrial performance) y <b>BPC-157</b> (recuperación + GI protection). Protocolos validados para body recomposition, optimización GH, sueño profundo y wellness preventivo C-suite.',
        'mi_eyebrow': 'Market Intelligence · Performance + GH optimization MX',
        'mi_h2': 'El hombre 40+ que ya no acepta <em class="italic">"es la edad".</em>',
        'mi_lede': 'El segmento wellness masculino 40-65 creció <b>+22%</b> en los últimos 2 años (Euromonitor 2025) · TRT clinics en MX expandieron <b>+35%</b> entre 2022-2024 (IQVIA). El paciente C-suite ya conoce las clínicas en USA (Maximus, Hone, Marek). Si tu clínica no integra GH stack peptídico, te lo vas a perder. Tesamorelin es el único secretagogo con aprobación FDA · diferenciador defendible.',
        'mi_stats': [
            ('+22%', 'Wellness masculino 40-65 (2022-2024)', 'Euromonitor Voice of Consumer 2025 · clínicas premium facturan ticket 3× vs 2020'),
            ('-50%', 'Decline GH natural 30-50 años', 'Documentado en endocrinología · justifica secretagogos peptídicos sobre HGH recombinante'),
            ('+35%', 'Crecimiento TRT clinics MX 2022-2024', 'IQVIA México · CDMX, MTY, GDL · ticket retainer $30-80k MXN/paciente/año'),
        ],
        'levers': [
            ('Lever #1 · Hombres 40+ wellness · explosión post-pandemia',
             'Pacientes ejecutivos 45-60 ya no aceptan "es la edad". Maximus, Hone, Marek (USA) crecen 100%+ anual. En MX, las clínicas TRT expandieron +35% entre 2022-2024 (IQVIA). El gap: la mayoría no integra GH stack peptídico · oportunidad clara para diferenciar.'),
            ('Lever #2 · GH peptídico · perfil seguridad superior a HGH recombinante',
             'CJC+Ipamorelin estimula pulso GH endógeno fisiológico (no exógeno). Sin supresión hipotalámica, sin riesgo de tumoración a dosis research, perfil regulatorio más favorable. Es la jugada inteligente para clínicas serias.'),
            ('Lever #3 · Tesamorelin · único FDA-approved · diferenciador único',
             'Aprobado por FDA (Egrifta · EMD Serono) para lipodistrofia HIV. Off-label: efecto selectivo sobre grasa visceral en pacientes 45+ con resistencia a TRT. La clínica que lo integra captura el segmento premium body recomposition.'),
        ],
        'use_cases': [
            ('💪 Composición corporal hombre 40+ (grasa abdominal)', 'Tesamorelin 1-2mg SC/día + CJC+Ipa nocturno · 8-12 sem. Reduce grasa visceral 18%+ documentado. <b>Ticket programa:</b> $25,000-45,000 MXN.'),
            ('😴 Sueño profundo · insomnio medio', 'Ipamorelin selectivo nocturno (sin cortisol) restaura ondas delta. Pacientes ejecutivos con awakening 3-4am · ticket $8-12k/4 semanas mantenimiento.'),
            ('🏋️ Recuperación atletas máster', 'Stack CJC+Ipa + BPC-157. Atletas crossfit/triatlón 40-55 con tendinopatías recurrentes. Programa 6-8 sem $18-28k MXN.'),
            ('🩺 Pre-TRT optimization', 'Pacientes con testo borderline (350-500 ng/dL) · CJC+Ipa primero antes de saltar a TRT exógeno. Plataforma para 6 meses de optimización antes de hormonal terapéutico.'),
            ('⚡ Wellness preventivo C-suite', 'Programa anual · Tesamorelin trimestre + CJC+Ipa nocturno + NAD+ IV mensual. <b>Retainer C-suite:</b> $80,000-150,000 MXN/año.'),
            ('🔥 Body recomposition severa post-Ozempic', 'Cliente perdió 15kg con GLP-1 pero "está flojo". Stack Tesamorelin + Ipamorelin recupera masa magra sin recuperar grasa. Cross-sell con SHRED.'),
        ],
        'personas': [
            ('Endocrinólogo HRT', '40-55 · clínica TRT/HRT · ticket $30-80k retainer/año · 80-150 pac/mes', 'Pacientes 40+ que llegan con testo borderline. TRT no es para todos · necesita tier intermedio antes de exógeno.', 'CJC+Ipa como pre-TRT · expande oferta sin canibalizar TRT · captura pacientes que no califican para hormonal todavía. Ticket adicional $15-25k/paciente/año.'),
            ('Médico deportivo masculino 40-55', '38-52 · enfoque atletas máster · ticket $5-15k/sesión · 100+ pac/mes', 'Atletas 40+ se quejan de "ya no recupero como antes". Fisioterapia + suplementos no escala el ROI.', 'Stack BPC-157 + CJC+Ipa · convierte clínica en "performance lab". Ticket protocolo 8 sem $15-30k MXN/paciente.'),
            ('Performance physician C-suite ejecutivos', '42-58 · concierge medicine · retainer $80-200k MXN/año por ejecutivo C-suite', 'Clientes pagan retainer alto pero protocolo es vitaminas + chequeo anual. Necesitan justificar ticket con outcomes medibles.', 'Programa Tesamorelin trimestre + body comp DEXA pre/post + CJC+Ipa nocturno + NAD+ IV. Convierte concierge en "human optimization retainer".'),
        ],
        'objections': [
            ('"¿No es lo mismo que HGH inyectable?"',
             'No · CJC+Ipa estimula pulso GH ENDÓGENO fisiológico. HGH es exógeno (suprime el eje natural). Perfil regulatorio y seguridad muy distintos · este es el diferenciador clave para tu paciente "informado".'),
            ('"¿Y si quiere TRT también?"',
             'Cross-compatible. Muchos pacientes hacen TRT + GH peptídico stack. Requiere monitoreo lipid + glucose · te apoyamos con protocol referencia.'),
            ('"Tesamorelin · ¿está disponible legal?"',
             'Approved por FDA (Egrifta) · alternativa research-grade es la única vía en MX. PEPTIQ aporta COA Janoshik por lote · facturación CFDI · documentación regulatoria lista.'),
        ],
        'family_estas_aqui': 'PRIME',
    },
    # ═══════════════════════════════════════════════════════════════════════
    'SHRED': {
        'intro_h2_em': 'la pérdida de peso premium.',
        'intro_lede': 'Cinco moléculas para clínicas de obesidad y nutrición funcional que ya saben que Ozempic no es suficiente: <b>Retatrutide</b> (triple GLP-1/GIP/Glucagón · -24% peso vs -15% Ozempic), <b>Tirzepatide</b> (dual · alternativa Mounjaro), <b>Tesamorelin</b> (preserva masa magra · selectivo grasa visceral), <b>BPC-157</b> (anti-catabólico · GI protection) y <b>Ipamorelin</b> (preservación muscular durante déficit). El stack post-Ozempic que tu competencia no está armando.',
        'mi_eyebrow': 'Market Intelligence · GLP-1 + obesidad MX',
        'mi_h2': 'GLP-1 transformó el mercado · <em class="italic">y dejó un gap.</em>',
        'mi_lede': 'Euromonitor (Sept 2025): <b>9% de la población global toma GLP-1 (14% en Norteamérica)</b>. Pero el efecto secundario silencioso es la pérdida de masa magra de 20-30g/día. Kate Farms acaba de lanzar línea exclusiva GLP-1 muscle preservation. Las clínicas MX tienen <b>gap evidente</b> · es donde tu protocolo SHRED PRO captura el premium del mercado bariátrico moderno.',
        'mi_stats': [
            ('14%', 'Población USA en GLP-1', 'Euromonitor Health & Wellness 2025 · cresta de adopción · MX siguiendo curva con 18-24 meses retraso'),
            ('-24%', 'Pérdida peso Retatrutide vs -15% Ozempic', 'Eli Lilly fase 3 NEJM 2024 · próxima generación blockbuster ($50bn forecast 2030)'),
            ('20-30g', 'Pérdida muscular/día con GLP-1', 'Documentado · justifica stack preservación con BPC + Ipamorelin · gap clínico que tu protocolo cubre'),
        ],
        'levers': [
            ('Lever #1 · GLP-1 reshaping global · gap muscle preservation',
             'Euromonitor 2025: 14% USA en GLP-1. Pacientes pierden peso pero "están flojos" · grasa visceral baja pero masa magra también. Kate Farms lanzó línea protein 2025. Clínicas que arman stack preservation capturan el ticket premium post-Ozempic.'),
            ('Lever #2 · Retatrutide superioridad documentada vs semaglutida',
             'Eli Lilly fase 3 NEJM 2024: -24% peso 48 sem vs -15% Ozempic. Triple agonist GLP-1/GIP/Glucagón · bloqueada en 3 vías metabólicas. Forecast $50bn mercado 2030 (JPMorgan). Las clínicas pioneras capturan ese segmento NOW.'),
            ('Lever #3 · Mexicano post-Ozempic = mercado huérfano premium',
             'Pacientes mexicanos high-net-worth que probaron Ozempic y "se atoraron" o "están flojos". Sin alternativa local de calidad. SHRED PRO (Retatrutide + Tesamorelin + BPC + Ipamorelin) es exactamente el protocolo que necesitan · ticket $14-20k MXN/paciente.'),
        ],
        'use_cases': [
            ('🔥 Pacientes meseta-ron en Ozempic', 'Cliente lleva 6 meses, perdió 8 kg, ya no baja. Switch a Retatrutide · titración lenta. Recuperan trayectoria sin efectos GI severos. Conversión típica.'),
            ('⚖️ Obesidad grado 2-3 (BMI 35+)', 'Pacientes elegibles bariátricos que rechazan cirugía. Retatrutide 4-12mg semanal + Tesamorelin diaria · 16-24 sem. <b>Ticket programa:</b> $30,000-55,000 MXN.'),
            ('💪 Preservación muscular durante GLP-1', 'Stack Ipamorelin + BPC-157 mientras paciente está en Retatrutide. Reduce 60% pérdida muscular. Add-on $8-12k al protocolo principal.'),
            ('🩹 Post-bariátrica con pérdida magra', 'Pacientes 12-24 meses post-bypass o sleeve · perdieron peso pero también colágeno + masa magra. Stack regenerativo $15-25k programa.'),
            ('🏋️ Body recomposition severa', 'Pacientes que quieren "perder 20kg sin perder músculo". Programa 6 meses Retatrutide + Tesamorelin + Ipa + BPC + DEXA pre/post. Ticket $80-120k MXN total.'),
            ('💉 Diabetes T2 con obesidad', 'Pacientes con HbA1c 7.5+ y BMI 32+. Retatrutide cubre triple acción metabólica · superior a sema solo. Cross-disciplinary con endocrinólogo.'),
        ],
        'personas': [
            ('Bariatric / obesity specialist', '40-55 · clínica obesidad · 100-200 pac/mes · ticket $5-30k según procedimiento', 'Pacientes obesidad grado 1-2 que rechazan cirugía · necesitan opción GLP-1 + soporte muscular. Ozempic es genérico · no diferencia.', 'Programa SHRED PRO · Retatrutide + Tesamorelin + Ipamorelin · ticket $30-55k vs $400k cirugía bariátrica · acceso al middle-tier huérfano.'),
            ('Endocrinóloga metabólica', '38-55 · enfoque diabetes T2 + obesidad · 150+ pac/mes · ticket $3-8k consulta', 'Pacientes diabetes con obesidad que requieren más que metformina + semaglutida. Frustrados con mesetas terapéuticas.', 'Switch a Retatrutide en mesetas · adherencia + outcomes superiores. Cross-sell con stack preservación. Convierte endocrino en "metabolic optimization clinic".'),
            ('Médico nutrición funcional', '35-50 · enfoque integral · 80-150 pac/mes · paquetes mensuales $4-12k', 'Pacientes pagan paquetes pero "no bajan suficiente". Necesitan herramienta farmacológica controlada para casos severos.', 'Retatrutide + protocolo nutricional + DEXA mensual · ticket retainer $8-15k/mes/paciente. Convierte nutrición en "weight management médico premium".'),
        ],
        'objections': [
            ('"¿Es legal Retatrutide en México?"',
             'Research-grade · no hay aprobación FDA aún (fase 3 completada). Tu paciente firma consentimiento informado · uso bajo criterio médico profesional. Te entregamos dossier científico + COA del lote para tu defensa documental.'),
            ('"¿Riesgo cardiovascular como Ozempic?"',
             'Retatrutide cardiovascular safety profile comparable a semaglutida en ensayos fase 3. Monitoreo standard cardio + lipid + thyroid · te apoyamos con protocolo de monitoreo y consent forms.'),
            ('"Mi paciente ya pagó 6 meses de Ozempic"',
             'Switch a Retatrutide es upgrade · perfil GI más tolerable + outcomes superiores documentados. Position como "siguiente nivel" no como "alternativa barata". Ticket adicional $5-10k/mes.'),
        ],
        'family_estas_aqui': 'SHRED',
    },
    # ═══════════════════════════════════════════════════════════════════════
    'SPA': {
        'intro_h2_em': 'el wellness 360°.',
        'intro_lede': 'Cinco moléculas signature para spa médico y wellness clinics premium: <b>TRINITY</b> (BPC + GHK-Cu + TB-500 blend · cascada regenerativa), <b>GHK-Cu</b> (copper peptide multi-uso), <b>BPC-157</b> (recuperación sistémica), <b>NAD+</b> (IV drip longevity · servicio bandera) y <b>Epithalon</b> (programa biological age VIP). Protocolos integrados para signature treatments, IV drips, longevity quarterly y membership Elite.',
        'mi_eyebrow': 'Market Intelligence · Spa médico + Wellness experiential',
        'mi_h2': 'El medspa que cobra <em class="italic">por experiencia, no por minutos.</em>',
        'mi_lede': 'Euromonitor (Sept 2025): <b>luxury experiential wellness +9% CAGR</b> · supera beauty, supplements y food. <b>25% paga +20%</b> por personalización basada en diagnóstico. La convergencia spa + medical es el tercer lever de mayor crecimiento. Tu spa que integra péptidos research-grade + IV drips + protocolos multi-semana se posiciona como referente medical-grade · ticket trimestre $30-80k MXN/paciente.',
        'mi_stats': [
            ('+9%', 'CAGR luxury experiential wellness', 'Euromonitor Health & Wellness 2025 · mayor que beauty, supplements y food'),
            ('25%', 'Pagan +20% por "personalización"', 'Voice of Consumer Beauty Survey 2025 · justifica protocolos individualizados con biomarcadores'),
            ('$80-250k', 'Gasto wellness anual VIP MX', 'C-suite ejecutivos + esposas · CDMX, MTY, San Pedro, GDL · sweet spot para signature retainer'),
        ],
        'levers': [
            ('Lever #1 · Experiential luxury wellness · explosión global',
             'Euromonitor confirma que el luxury experiential wellness es el segmento de mayor crecimiento (+9% CAGR) · supera beauty, supplements y food. Las pacientes premium ya no compran sesiones · compran transformaciones documentables. Tu spa que pivote captura ese ticket.'),
            ('Lever #2 · Convergencia spa + medical · medspa es el futuro',
             'Spa puro pierde · medspa con péptidos research-grade + IV drips + biomarcadores se posiciona como medical-grade. El paciente VIP paga premium por "ciencia + experiencia VIP" · no por uno solo de los dos.'),
            ('Lever #3 · Multi-protocolo = retainer · no transacción',
             'El upgrade del modelo spa es de "sesión de $3k" a "retainer de $30k trimestre". TRINITY 8-sem + NAD+ IV mensual + Epithalon Khavinson + GHK-Cu sistémico = paquete con múltiples touchpoints VIP que convierte cliente en miembro Elite.'),
        ],
        'use_cases': [
            ('✨ Signature TRINITY treatment 6-8 sem', 'Mesoterapia facial integral con TRINITY (BPC+GHK+TB-500). 6-8 sesiones quincenales. <b>Ticket paquete:</b> $35,000-55,000 MXN. El "tratamiento bandera" del spa.'),
            ('💧 IV drip NAD+ longevity (servicio signature)', '500-1000mg infusión 60-90 min · ambiente premium · pacientes recurrentes mensuales. <b>Ticket:</b> $4,000-8,000 MXN. Spas que lo integran facturan +$120k USD/año solo de esto.'),
            ('🕰️ Programa biological age quarterly', 'Stack 12 sem · NAD+ + Epithalon + GHK-Cu sistémico + biomarcadores pre/post (Horvath/TruDiagnostic). <b>Ticket programa:</b> $40,000-80,000 MXN/trimestre. Retainer ideal.'),
            ('💍 Pre-evento social (boda, gala) drips', 'NAD+ IV + GHK-Cu mesoterapia 1-2 semanas antes. Servicio premium pre-eventos. Ticket $8-15k/sesión. Re-orden cada evento.'),
            ('🩹 Post-procedure VIP (cirugía estética + recovery)', 'Cross-sell con cirujano plástico · paciente post-BBL/abdominoplastia integra TRINITY + BPC sistémico para acelerar cicatrización. Add-on $8-15k al ticket cirugía.'),
            ('💎 Membership Elite con descuentos perpetuos', 'Cliente acumula >$20k MXN gastados · Elite membership con -10% perpetuo + early access lanzamientos + concierge dedicado. Conversión a LTV $200k+/cliente.'),
        ],
        'personas': [
            ('Spa médico premium owner', '40-55 · 1-3 cabinas + área IV · 80-200 pac/mes · ticket $3-15k/sesión', 'Compite contra spas hotel y clínicas estéticas. Necesita diferenciador "medical-grade" para justificar premium pricing.', 'TRINITY signature + NAD+ IV drip · convierte spa en medspa. Ticket pasa de transacción $3k a retainer trimestre $30k. ROI 4× en pacientes elite.'),
            ('Wellness clinic boutique high-end', '38-50 · enfoque integral · 50-100 pac/mes · paquetes mensuales $8-25k', 'Pacientes pagan paquetes pero "se aburren" después de 3 meses. Necesita variedad de protocolos para retención.', 'Multi-protocolo PEPTIQ · roto entre TRINITY (estético) · NAD+ IV (longevity) · BPC sistémico (recovery). Cliente nunca se aburre · LTV 2× anual.'),
            ('Medspa franquicia premium', '35-50 · operación multi-sucursal · 200-500 pac/mes total · ticket promedio $4-8k', 'Estandarización a través de sucursales · pero quieren diferenciador signature único.', 'TRINITY como "tratamiento bandera de la marca" · trainings al equipo · co-branding · COA Janoshik en cada vial. Diferenciador defendible vs franquicia competidora.'),
        ],
        'objections': [
            ('"Mis pacientes no conocen péptidos · ¿cómo los educo?"',
             'Te entregamos: (1) materiales co-branded para tu paciente, (2) video training para tu equipo, (3) PDF protocolar con FAQ del paciente, (4) script de venta probado en clínicas pioneras. Tú solo aplicas · nosotros educamos.'),
            ('"¿IV drip requiere licencia especial?"',
             'Aplicación intravenosa requiere médico/enfermero certificado · estándar para cualquier IV. PEPTIQ aporta NAD+ research-grade con COA · tu equipo lo administra bajo tu protocolo médico.'),
            ('"¿Margen versus mis tratamientos láser actuales?"',
             'Margen TRINITY 8 sesiones: 75-80% (vs 50-60% láser amortizado). Sin equipo capital. Ticket promedio igual o superior. ROI por hora de cabina muy superior · te apoyamos con cálculo financiero.'),
        ],
        'family_estas_aqui': 'SPA',
    },
}
