"""Extra per-line data: tier_products, coa_samples, biblio.
Merged into DEEP dict at runtime.
"""

EXTRA = {
    "WOLVERINE": {
        "tier_products": [
            ("BPC-157 10mg", "Pentadecapéptido · gold standard regenerativo", 2999),
            ("TB-500 10mg", "Thymosin Beta-4 · migración celular", 3799),
            ("KPV 10mg", "Tripéptido α-MSH · anti-inflamatorio", 2899),
            ("Wolverine Stack", "BPC + TB-500 · 4-8 sem recuperación", 5499),
            ("Wolverine PRO", "Stack avanzado 8-12 sem", 6999),
            ("LL-37 10mg", "Catelicidina · defensa inmune", 4299),
            ("MGF 10mg", "Mechano Growth Factor · hipertrofia", 4499),
        ],
        "coa_samples": [
            {"name": "BPC-157 10mg", "lot": "BPC-2026-Q2-001", "purity": "99.654%", "mass": "1419.55 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "12-ene-2026"},
            {"name": "TB-500 10mg", "lot": "TB-2026-Q2-003", "purity": "99.328%", "mass": "894.46 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "08-feb-2026"},
            {"name": "KPV 10mg", "lot": "KPV-2026-Q1-005", "purity": "99.12%", "mass": "342.43 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "15-feb-2026"},
            {"name": "MGF 10mg", "lot": "MGF-2026-Q1-001", "purity": "98.9%", "mass": "2867.3 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "20-feb-2026"},
        ],
        "biblio": [
            ("BPC-157 · Body Protection Compound",
             "1,200+ estudios preclínicos 1991-presente. Sikiric et al. (Universidad Zagreb). Aislado del jugo gástrico humano. Angiogénesis vía VEGFR2/eNOS · referente regeneración tendón, ligamento, mucosa GI."),
            ("TB-500 · Thymosin Beta-4 fragment",
             "Goldstein et al. (NIH). Fragmento Timosina Beta-4. Mecanismo: secuestra G-actina libre · regula citoesqueleto · activa macrófagos M2 pro-reparadores. Sinérgico con BPC-157 · cubre vía complementaria."),
            ("KPV · α-MSH C-terminal tripeptide",
             "Lipton et al. Tripéptido Lys-Pro-Val · fragmento C-terminal α-MSH. Anti-inflamatorio sin inmunosupresión · modula NF-κB y MC1R · útil intestinal (UC, Crohn off-label) y dérmico (acné, hidradenitis)."),
            ("Pevec et al. 2021 · Tendinopatía crónica",
             "Estudio observacional · BPC-157 reduce 40-60% tiempo recuperación tendón Aquiles vs fisioterapia convencional. n=24 atletas amateurs."),
            ("Bock-Marquette 2004 · TB-500 cardíaco",
             "TB-500 mejora función ventricular post-IAM · documentado en cardiología regenerativa. Modelo animal · evidencia preclínica de cell migration en tejido cardíaco."),
            ("CONAMED 2024 · Cirugías ortopédicas MX",
             "220k cirugías ortopédicas/año · ~30% reportan recuperación lenta o cicatrización subóptima. Gap regenerativo claro para protocolos peptídicos en post-operatorio."),
        ],
    },

    "HIGHLANDER": {
        "tier_products": [
            ("NAD+ 1000mg", "Coenzima · 500+ reacciones · sirtuinas", 5499),
            ("Epithalon 50mg", "Tetrapéptido AEDG · telomerasa Khavinson", 6799),
            ("MOTS-c 10mg", "Péptido mitocondrial · master regulator", 4799),
            ("Pinealon 10mg", "Tripéptido pineal · circadian", 4299),
            ("Thymalin 10mg", "Extracto tímico · inmunidad longevity", 4999),
            ("Thymosin α-1 10mg", "Péptido tímico sintético · T-cell", 5999),
            ("Highlander Stack", "NAD+ + Epithalon + MOTS-c · 12 sem", 14999),
        ],
        "coa_samples": [
            {"name": "NAD+ 1000mg", "lot": "NAD-2026-Q1-012", "purity": "99.500%", "mass": "663.43 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "20-feb-2026"},
            {"name": "Epithalon 50mg", "lot": "EPI-2026-Q1-008", "purity": "99.32%", "mass": "390.39 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "10-ene-2026"},
            {"name": "MOTS-c 10mg", "lot": "MOTS-2026-Q1-003", "purity": "99.10%", "mass": "2174.5 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "05-feb-2026"},
            {"name": "Pinealon 10mg", "lot": "PIN-2026-Q1-002", "purity": "99.05%", "mass": "418.45 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "18-feb-2026"},
        ],
        "biblio": [
            ("NAD+ · Nicotinamide Adenine Dinucleotide",
             "Sinclair et al. (Harvard) · Verdin et al. (Buck Institute). Cofactor 500+ reacciones · activa 7 sirtuinas SIRT1-7. Decline ~50% entre 40-60 años. Pico circadiano ZT 14 (inicio oscuridad, +40-53%)."),
            ("Epithalon (AEDG) · Khavinson Tetrapeptide",
             "Khavinson 1980-presente · St. Petersburg Institute of Bioregulation. Único péptido con evidencia preclínica reproducible de telomerase reactivation. Protocolo cíclico 10-on/20-off."),
            ("MOTS-c · Mitochondrial-derived peptide",
             "Lee et al. 2015 · USC. 16-aa péptido encoded by mtDNA. Master regulator metabólico · AMPK activation · insulin sensitivity · gasto energético basal."),
            ("Pinealon · Pineal Tripeptide",
             "Khavinson Research. Tripéptido Glu-Asp-Arg. Regula expresión génica pineal · normaliza melatonina endógena · neuroprotector documentado en hippocampus."),
            ("Thymalin · Thymic Extract",
             "Khavinson 1970s-presente. Extracto tímico bovino purificado · reactivates T-cell function · normaliza CD4/CD8 ratio."),
            ("CLOCK:BMAL1 · NAMPT · SIRT1 cycle",
             "Sahar & Sassone-Corsi (UC Irvine). NAD+ no es estático: oscilación circadiana estricta. NAMPT (enzima limitante) sintetiza NAD+ · SIRT1 frena CLOCK:BMAL1 reseteando ciclo. Protege onda metabólica."),
            ("NMN/NR · Lifespan extension data",
             "Mills et al. 2016 (Cell Metabolism). Restauración precursores NAD+ extiende esperanza de vida hasta +30% en modelos · restaura vitalidad muscular y neurológica."),
        ],
    },

    "PRIME": {
        "tier_products": [
            ("CJC + Ipamorelin 10mg", "GH Stack · sinergia secretagogo", 5499),
            ("Tesamorelin 10mg", "GHRH análogo · grasa visceral", 7499),
            ("Ipamorelin 10mg", "Selectivo · sin cortisol/prolactina", 3099),
            ("Sermorelin 10mg", "Secretagogo clásico · sleep quality", 3499),
            ("Follistatin 5mg", "Inhibidor miostatina · hipertrofia", 12999),
            ("PT-141 10mg", "Bremelanotide · función sexual", 5499),
            ("Semax 10mg", "Heptapéptido nootrópico · BDNF", 2899),
        ],
        "coa_samples": [
            {"name": "CJC+Ipamorelin 10mg", "lot": "CJC-2026-Q1-006", "purity": "99.42%", "mass": "Blend 5+5mg",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "12-feb-2026"},
            {"name": "Tesamorelin 10mg", "lot": "TES-2026-Q1-004", "purity": "99.18%", "mass": "5135.9 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "08-feb-2026"},
            {"name": "Ipamorelin 10mg", "lot": "IPA-2026-Q1-003", "purity": "99.51%", "mass": "711.85 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "05-ene-2026"},
            {"name": "Semax 10mg", "lot": "SEM-2026-Q1-002", "purity": "99.7%", "mass": "813.94 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "15-feb-2026"},
        ],
        "biblio": [
            ("CJC-1295 · GHRH analog (DAC)",
             "Ionescu & Frohman 2006 (J Clin Endocrinol Metab). Análogo GHRH con DAC (drug affinity complex) · prolonga vida media a 8 días · multiplica frecuencia de pulsos GH endógenos. \"El Promotor\"."),
            ("Ipamorelin · Selective GHRP",
             "Raun et al. 1998. Pentapéptido selectivo · agonista GHS-R1a · amplifica amplitud del pulso GH SIN elevar cortisol ni prolactina. \"El Hype Man\". Perfil de seguridad limpio."),
            ("Tesamorelin · GHRH analog · FDA approved",
             "Aprobado FDA (Egrifta · EMD Serono) para lipodistrofia HIV. Único secretagogo GH con aprobación regulatoria internacional. Selectividad documentada sobre grasa visceral."),
            ("Sermorelin · Original GHRH-29",
             "Walker 1994. Secretagogo original · 29 aminoácidos · vida media muy corta. Historial de seguridad impecable. Punto de partida para mejorar calidad sueño profundo (Fase 3/4 REM)."),
            ("Follistatin · Myostatin inhibitor",
             "Lee et al. 2007. Inhibidor directo de miostatina (freno genético del crecimiento muscular). Desactiva freno permitiendo hipertrofia sin precedentes."),
            ("Semax · ACTH-derived heptapeptide",
             "Ashmarin et al. (Russia). Heptapéptido nootrópico · BDNF upregulation · enfoque sin estimulante. Aprobado en Rusia desde 1982 sin reportes de tolerancia."),
            ("PT-141 · Bremelanotide · FDA Vyleesi 2019",
             "Pfaus et al. Análogo melanocortina · mecanismo central neural (no vascular como sildenafilo). Aprobado FDA 2019 (Vyleesi) para HSDD femenino."),
        ],
    },

    "SHRED": {
        "tier_products": [
            ("Retatrutide 30mg", "Triple agonista GLP-1/GIP/Glucagón", 12999),
            ("Tirzepatide 30mg", "Doble agonista GLP-1/GIP · Mounjaro alt", 8999),
            ("AOD-9604 5mg", "Fragmento HGH 176-191 · lipolisis pura", 3999),
            ("Cagrilintide-Sema 10mg", "Amilina + GLP-1 · saciedad química", 7499),
            ("Mazdutide 10mg", "Dual GLP-1/Glucagón · próximo bloque", 6999),
            ("5-Amino-1MQ 10mg", "Inhibidor NNMT · metabolismo", 3499),
            ("Tesamorelin 10mg", "Grasa visceral · preservación muscular", 7499),
        ],
        "coa_samples": [
            {"name": "Retatrutide 30mg", "lot": "RET-2026-Q1-001", "purity": "99.42%", "mass": "4731.5 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "10-feb-2026"},
            {"name": "Tirzepatide 30mg", "lot": "TIR-2026-Q1-008", "purity": "99.16%", "mass": "4813.5 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "05-feb-2026"},
            {"name": "AOD-9604 5mg", "lot": "AOD-2026-Q1-002", "purity": "99.05%", "mass": "1815.0 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "20-ene-2026"},
            {"name": "Mazdutide 10mg", "lot": "MAZ-2026-Q1-001", "purity": "98.95%", "mass": "4500.5 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "18-feb-2026"},
        ],
        "biblio": [
            ("Retatrutide · Triple G agonist · Eli Lilly",
             "Jastreboff et al. NEJM 2024 (TRIUMPH). Triple agonista GLP-1/GIP/Glucagón. Pérdida peso -24.2% en 48 semanas vs -15% semaglutide. Próximo blockbuster · forecast $50bn 2030."),
            ("Tirzepatide · SURMOUNT-1 fase 3",
             "Eli Lilly · NEJM 2022 (SURMOUNT-1). Doble agonista GLP-1/GIP. Aprobado FDA 2022 (Mounjaro/Zepbound). Pérdida peso 22% promedio · primera molécula incretínica dual."),
            ("AOD-9604 · HGH fragment 176-191",
             "Heffernan et al. 2001. Fragmento aislado de molécula HGH. Combate bloqueo de insulina sobre células grasas. Funciona sólo en sinergia con déficit calórico (\"ayuno artificial\")."),
            ("Cagrilintide-Semaglutide · CagriSema",
             "Novo Nordisk fase 2/3. Amilina (cagrilintide) + GLP-1 (semaglutide). Saciedad como \"decisión química\". Define la nueva categoría de control de peso."),
            ("5-Amino-1MQ · NNMT inhibitor",
             "Kraus et al. 2014 (Nature). Inhibidor NNMT (enzima que silencia eficiencia metabólica en tejido adiposo). Restaura producción NAD+ adipocitaria."),
            ("Mazdutide · LY3437943",
             "Innovent / Eli Lilly fase 3. Dual GLP-1/Glucagón agonist. Resultados fase 3 muestran pérdida de peso de nivel quirúrgico (>20%) en 48 semanas."),
        ],
    },

    "GLOW": {
        "tier_products": [
            ("GHK-Cu 100mg", "Copper tripeptide · síntesis colágeno", 3799),
            ("AHK-Cu 50mg", "Hair copper peptide · folículo", 3299),
            ("Trinity 70mg", "BPC + GHK + TB-500 · cascada", 7499),
            ("LL-37 10mg", "Catelicidina · piel + inmunidad", 4299),
            ("BPC-157 10mg", "Cicatrización post-procedimiento", 2999),
            ("GLOW Essential Stack", "Trinity + agua bact · 6-8 sem", 7499),
            ("GLOW PRO Stack", "Trinity + GHK-Cu · 12 sem", 11999),
        ],
        "coa_samples": [
            {"name": "GHK-Cu 100mg", "lot": "GHK-2026-Q1-004", "purity": "99.128%", "mass": "402.92 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo azul-gris", "date": "02-feb-2026"},
            {"name": "Trinity 70mg", "lot": "TRI-2026-Q1-007", "purity": "99.4% promedio", "mass": "Blend 3 péptidos",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "15-feb-2026"},
            {"name": "AHK-Cu 50mg", "lot": "AHK-2026-Q1-002", "purity": "99.05%", "mass": "356.85 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo azul-claro", "date": "20-ene-2026"},
            {"name": "LL-37 10mg", "lot": "LL37-2026-Q1-003", "purity": "98.85%", "mass": "4493.3 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "10-feb-2026"},
        ],
        "biblio": [
            ("GHK-Cu · Copper Tripeptide-1",
             "Pickart 1973-presente · 50 años research. Glycyl-Histidyl-Lysyl-Cu²⁺. Modula 4,192 genes de reparación tisular. Ingrediente #2 más rápido en anti-aging premium global (Euromonitor 2025 · CAGR 16.9%)."),
            ("AHK-Cu · Hair Copper Tripeptide",
             "Variante estructural GHK con afinidad folicular. Estimula anagen · reduce miniaturización. Adyuvante mesoterapia capilar."),
            ("Trinity Blend · BPC + GHK + TB-500",
             "Formulación propietaria PEPTIQ. Sinergia entre angiogénesis (BPC), síntesis colágeno (GHK) y migración celular (TB-500). Triple cascada regenerativa en una formulación."),
            ("LL-37 · Cathelicidin antimicrobial peptide",
             "Sørensen et al. 1997. Catelicidina humana · péptido antimicrobiano endógeno. Efecto en piel (acné, eczema) e inmunidad sistémica. Investigación emergente en cicatrización dérmica."),
            ("Pickart 2018 · Copper peptides post-laser",
             "Reducción 50% tiempo recuperación CO₂ fraccionado. Estándar emergente medicina estética premium. Mecanismo: SPARC/decorina · inhibe MMPs."),
            ("Voice of Consumer Beauty Survey 2025 (n=12,704)",
             "27% paga +20% por formulación medicada · 25% por eficacia probada · 25% por personalización basada en diagnóstico."),
            ("Statista MX 2025 · Mercado estética MX",
             "USD 2.8 bn 2024 · CAGR +12% a 2029. Pacientes que cobran $5-15k MXN/procedimiento ya no aceptan cremas · buscan respaldo molecular."),
        ],
    },

    "SPA": {
        "tier_products": [
            ("Trinity 70mg", "Signature blend · servicio bandera", 7499),
            ("NAD+ 1000mg", "IV drip longevity · ticket premium", 5499),
            ("GHK-Cu 100mg", "Copper peptide multi-uso", 3799),
            ("BPC-157 10mg", "Recuperación sistémica", 2999),
            ("Epithalon 50mg", "Programa biological age VIP", 6799),
            ("SPA Signature Pkg", "Trinity 8 sem · pre-evento", 19999),
            ("Elite Quarterly Retainer", "Multi-protocolo trimestre", 79999),
        ],
        "coa_samples": [
            {"name": "Trinity 70mg", "lot": "TRI-2026-Q1-007", "purity": "99.4% promedio", "mass": "Blend 3 péptidos",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "15-feb-2026"},
            {"name": "NAD+ 1000mg", "lot": "NAD-2026-Q1-012", "purity": "99.500%", "mass": "663.43 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "20-feb-2026"},
            {"name": "BPC-157 10mg", "lot": "BPC-2026-Q2-001", "purity": "99.654%", "mass": "1419.55 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "12-ene-2026"},
            {"name": "Epithalon 50mg", "lot": "EPI-2026-Q1-008", "purity": "99.32%", "mass": "390.39 Da",
             "endo": "<0.125 EU/mg", "color": "Polvo blanco", "date": "10-ene-2026"},
        ],
        "biblio": [
            ("Trinity · Triple peptide blend",
             "Formulación propietaria PEPTIQ. Sinergia BPC-157 (angiogénesis) + GHK-Cu (síntesis colágeno) + TB-500 (migración celular). Producto signature spa médico premium."),
            ("NAD+ · IV drip longevity protocols",
             "Sinclair Lab Harvard · Verdin Buck Institute. IV 250-500mg 60-90 min absorción 100% · ideal sesiones premium · servicio signature de spa médico."),
            ("Epithalon Khavinson · Biological age",
             "Khavinson 1980-presente. Tetrapéptido AEDG con evidencia preclínica de telomerase reactivation. Protocolo cíclico 10-on/20-off · ideal programa quarterly retainer."),
            ("Euromonitor H&W Sept 2025 · Luxury experiential wellness",
             "Segmento de mayor crecimiento global +9% CAGR · supera beauty, supplements y food. Pacientes premium ya no compran sesiones · compran transformaciones documentables."),
            ("Voice of Consumer Beauty 2025 · Personalización",
             "25% paga +20% por personalización basada en diagnóstico (n=12,704). Justifica protocolos individualizados con biomarcadores pre/post."),
            ("Sahar & Sassone-Corsi · NAD+ circadian peak",
             "Pico principal NAD+ en ZT 14 (inicio oscuridad, +40-53%). Máxima capacidad de reparación celular SIRT1. Protocolo IV nocturno alinea con peak fisiológico."),
        ],
    },
}
